version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 3.1
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore 
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build 
      - echo Test started on `date`
      - dotnet test 
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -o testing
      - cd testing
      - zip ../test.zip *
      - aws s3 cp ../test.zip s3://dotset
      
artifacts:
  files:
    - ./test.zip
